# Configure web worker compilation for Flutter Web using build_web_compilers.
# This ensures web/*.dart (e.g., web/worker.dart) is compiled with dart2js.

targets:
  $default:
    builders:
      build_web_compilers:entrypoint:
        generate_for:
          - web/**.dart
        options:
          compiler: dart2js
        dev_options:
          dart2js_args:
            - --no-minify
        release_options:
          dart2js_args:
            - -O4
