name: remote_cache_sync
description: "Remote cache synchronization toolkit for Flutter with Appwrite, PocketBase, and Supabase adapters."
version: 0.1.4
homepage: https://topmoveright.github.io/remote_cache_sync
repository: https://github.com/topmoveright/remote_cache_sync
issue_tracker: https://github.com/topmoveright/remote_cache_sync/issues
documentation: https://topmoveright.github.io/remote_cache_sync
topics:
  - cache
  - sync
  - drift
  - wasm
  - flutter-web

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.8.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  drift: ^2.28.1
  drift_flutter: ^0.2.5
  path_provider: ^2.1.5
  supabase_flutter: ^2.6.0
  appwrite: ">=11.0.1 <18.0.0"
  pocketbase: ">=0.17.0 <0.24.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  drift_dev: ^2.28.1
  build_runner: ^2.6.0
  build_web_compilers: ^4.2.1

executables:
  web_setup: web_setup


